apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: langperf-apps
  namespace: langperf
  labels:
    release: kube-prom-stack
spec:
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/part-of: langperf
